apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  serviceAccountName: secretsmanagerrw
  volumes:
    - name: vol
      emptyDir:
        medium: Memory
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo $(cat /tmp/CATS_N_DOGS) && sleep 3600']
    volumeMounts:
      - name: vol
        mountPath: /tmp
  initContainers:
  - name: aws-secrets-manager
    image: jicowan/aws-secrets-manager:v0.2
    env:
      - name: AWS_REGION
        value: "us-east-1"
      - name: SECRET_NAME
        value: "catsndogs"
      - name: MOUNT_NAME
        value: "CATS_N_DOGS"
    volumeMounts:
      - name: vol
        mountPath: /tmp
